In [1]:
import numpy as np

In [2]:
# now we have a 2D array list
arr_list = [np.random.randn(5, 4) for i in range(3)]
arr_list

[array([[-0.19631471,  1.18265735,  0.01115997,  0.35394978],
        [-0.56157284, -0.5680715 , -0.98296265,  0.34585843],
        [-0.22428761,  1.64217638, -1.1317652 , -1.15891401],
        [-0.72019713,  0.09260752, -0.11745142, -0.24545703],
        [-0.17738026,  0.24016289,  0.95741487, -0.99287351]]),
 array([[-0.32503747, -1.72449159,  0.61351185, -0.88492633],
        [ 1.28655518, -1.43862279, -0.58063132,  0.45342796],
        [ 2.75688973, -0.00567465,  0.0905661 , -0.64504926],
        [-1.12371857,  0.15618741, -0.78724607,  0.54342605],
        [-0.14151782,  0.08112033,  0.36778556, -1.87403808]]),
 array([[-0.23090838, -1.13721595, -0.86147699,  1.27833749],
        [-0.70476703, -0.27766168, -0.8706251 , -0.30448968],
        [ 1.21921044,  0.37740295,  0.2057331 ,  0.58679055],
        [-1.83116096,  1.00002866, -0.30624256,  0.62135573],
        [-1.16082085,  0.30575234,  0.72810196, -0.55396841]])]

In [3]:
# convert it to a 3D array in numpy
a3 = np.array(arr_list)
a3

array([[[-0.19631471,  1.18265735,  0.01115997,  0.35394978],
        [-0.56157284, -0.5680715 , -0.98296265,  0.34585843],
        [-0.22428761,  1.64217638, -1.1317652 , -1.15891401],
        [-0.72019713,  0.09260752, -0.11745142, -0.24545703],
        [-0.17738026,  0.24016289,  0.95741487, -0.99287351]],

       [[-0.32503747, -1.72449159,  0.61351185, -0.88492633],
        [ 1.28655518, -1.43862279, -0.58063132,  0.45342796],
        [ 2.75688973, -0.00567465,  0.0905661 , -0.64504926],
        [-1.12371857,  0.15618741, -0.78724607,  0.54342605],
        [-0.14151782,  0.08112033,  0.36778556, -1.87403808]],

       [[-0.23090838, -1.13721595, -0.86147699,  1.27833749],
        [-0.70476703, -0.27766168, -0.8706251 , -0.30448968],
        [ 1.21921044,  0.37740295,  0.2057331 ,  0.58679055],
        [-1.83116096,  1.00002866, -0.30624256,  0.62135573],
        [-1.16082085,  0.30575234,  0.72810196, -0.55396841]]])

In [4]:
# give a test
b = np.array([1,2,3])
b

array([1, 2, 3])

In [5]:
# to sum them up
t = np.zeros([5, 4])
for i in range(3):
    t += b[i] * arr_list[i]
    pass
t

array([[-1.53911479, -5.67797366, -1.34624731,  2.41910957],
       [-0.10276356, -4.27830212, -4.75610061,  0.33924531],
       [ 8.94712316,  2.76303593, -0.33343371, -0.68864088],
       [-8.46111715,  3.40506834, -2.61067125,  2.70546226],
       [-3.94287847,  1.31966057,  3.87729187, -6.40285489]])

In [6]:
# the same as below
(a3.T@b).T

array([[-1.53911479, -5.67797366, -1.34624731,  2.41910957],
       [-0.10276356, -4.27830212, -4.75610061,  0.33924531],
       [ 8.94712316,  2.76303593, -0.33343371, -0.68864088],
       [-8.46111715,  3.40506834, -2.61067125,  2.70546226],
       [-3.94287847,  1.31966057,  3.87729187, -6.40285489]])

In [7]:
(a3.T@b).T == t

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])