In [1]:
import numpy as np

In [2]:
b = np.array([5, 8, 9])

In [3]:
a = np.array([
    [1, 2],
    [2, 3],
    [5, 2]
])
np.linalg.lstsq(a, b, rcond=None)[0]

array([1., 2.])

In [4]:
a = np.array([
    [1, 2, 3],
    [2, 3, 2],
    [5, 2, 8]
])
np.linalg.lstsq(a, b, rcond=None)[0]

array([ 1.00000000e+00,  2.00000000e+00, -1.42166814e-15])

In [5]:
a = np.array([
    [1, 2, 3, 1],
    [2, 3, 2, 3],
    [5, 2, 8, 3]
])
np.linalg.lstsq(a, b, rcond=None)[0]

array([0.12698413, 1.47619048, 0.34920635, 0.87301587])